;    clock: Clock application for the Commodore 64.
;    Copyright (C) 2022  C64PECTRE
;
;    This program is free software: you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation, either version 3 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with this program.  If not, see https://www.gnu.org/licenses/.
;
;    Contact: https://github.com/c64pectre/clock/ create an issue

C_A =   1
C_B =   2
C_C =   3
C_D =   4
C_E =   5
C_F =   6
C_G =   7
C_H =   8
C_I =   9
C_J =  10
C_K =  11
C_L =  12
C_M =  13
C_N =  14
C_O =  15
C_P =  16
C_Q =  17
C_R =  18
C_S =  19
C_T =  20
C_U =  21
C_V =  22
C_W =  23
C_X =  24
C_Y =  25
C_Z =  26
LSB =  27
RSB =  29
SPC =  32
LPA =  40
RPA =  41
PLS =  43
MIN =  45
PER =  46
DIV =  47
C_0 =  48
C_1 =  49
C_2 =  50
C_3 =  51
C_4 =  52
C_5 =  53
C_6 =  54
C_7 =  55
C_8 =  56
C_9 =  57
COL =  58
HOR =  64
VER =  66
DOT =  81
SW  = 109
NE  = 110
NW  = 112
SE  = 125
R_A = 129
R_B = 130
R_C = 131
R_D = 132
R_E = 133
R_F = 134
R_G = 135
R_H = 136
R_I = 137
R_J = 138
R_K = 139
R_L = 140
R_M = 141
R_N = 142
R_O = 143
R_P = 144
R_Q = 145
R_R = 146
R_S = 147
R_T = 148
R_U = 149
R_V = 150
R_W = 151
R_X = 152
R_Y = 153
R_Z = 154

R_0 =  176
R_1 =  177
R_2 =  178
R_3 =  179
R_4 =  180
R_5 =  181
R_6 =  182
R_7 =  183
R_8 =  184
R_9 =  185
